version: '3.8'

services:
  resto-coreservice:
    build: ./resto-coreservice
    ports:
      - "8000:8000"
    environment:
      - MENU_SERVICE_URL=http://resto-menuservice:8001
      - CART_SERVICE_URL=http://resto-cartservice:8002
      - DB_HOST=db
      - DB_NAME=coreservice
      - DB_USER=postgres
      - DB_PASSWORD=Ahgase07
    depends_on:
      - db
      - resto-menuservice
      - resto-cartservice

  resto-menuservice:
    build: ./resto-menuservice
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=db
      - DB_NAME=coreservice
      - DB_USER=postgres
      - DB_PASSWORD=Ahgase07
    depends_on:
      - db

  resto-cartservice:
    build: ./resto-cartservice
    ports:
      - "8002:8002"
    environment:
      - DB_HOST=db
      - DB_NAME=coreservice
      - DB_USER=postgres
      - DB_PASSWORD=Ahgase07
    depends_on:
      - db

  resto-clientservice:
    build: ./resto-clientservice
    ports:
      - "3000:3000"
    depends_on:
      - resto-coreservice

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=coreservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ahgase07
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
